---
title: "data_analysis_atelsek_1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#Installing packages

#install.packages("data.table")
#install.packages("tidyverse")
#install.packages("janitor")
#install.packages("arcos")
#install.packages("tidycensus")
#install.packages("mapview")
#install.packages("ggthemes")
#install.packages("scales")


# Loading packages

library(tidyverse)
library(janitor)
library(arcos)
library(tidycensus)
library(mapview)
library(ggthemes)
library(scales)
library(data.table)

```

```{r}

# Importing and cleaning HIV data

# Reading data

hiv.data.1 <- read_csv("data/HIV_DATA.csv")
                     
```

```{r}

# Reading data again

hiv.data.2 <- read.csv("data/HIV_DATA.csv")

```

```{r}


# Removing all counties for which HIV data was suppressed

hiv.data.1 <- hiv.data.1 %>%
  filter(Cases != "Data suppressed")

hiv.data.2 <- hiv.data.2 %>%
  filter(Cases != "Data suppressed")



# Removing unecessary columns from each dataframe to simplify the join

hiv.data.1 <- 
  select(hiv.data.1,-c(Geography, Indicator, Population))

hiv.data.2 <- 
  select(hiv.data.2, -c(Geography, Indicator, FIPS, Cases, Rate.per.100000))


```


```{r}

# Merging hiv.data.1 (which has accurate FIPS code information) and hiv.data.2 (which has accurate population information)

hiv.data <- merge(hiv.data.1, hiv.data.2, by=c("Year","County", "State")) 

# SUCCESS 

# Making column names lowercase

hiv.data <- clean_names(hiv.data)

```

```{r}

# Renaming columns to make the dataframe easier to read

 hiv.data <- hiv.data %>% 
  setnames(old=c("rate_per_100000"), new=c("hiv_rate_per_100k")) %>%
  setnames(old=c("cases"), new=c("hiv_cases")) 


```

```{r}

# Q1: How many counties had "data suppressed" as their value?

hiv.data.raw <- read.csv("data/HIV_DATA.csv")

hiv.data.raw %>%
  filter(Cases=="Data suppressed")

# Answer: 7,620. That's a pretty significant number, and it might become a problem later on in the project.

```

```{r}

# Q2: Which county had the highest rate of HIV diagnoses? When?

hiv.data %>%
  arrange(desc(hiv_rate_per_100k))

# A: Calhoun County, GA, in 2008. 

```

``` {r}

# Q3: How many counties have a rate of 0?

hiv.data %>%
  filter(hiv_cases=="0")

# A: 1,161.


```

```{r}

# Loading in ARCOS opioid data

# Storing one of our API keys as an object called key

key <- "uO4EK6I"

# Pull down ARCOS data for pills per county per year

arcos_county_pills_per_year <- summarized_county_annual(key = key) %>%
  clean_names()

```

``` {r}

# The ARCOS database only covers the years 2006-2012. I'm going to remove the years that don't match up from the HIV data. For some reason it isn't working when I list the years I want to remove, so I guess I'll just do it four times.

hiv.data <- hiv.data %>%
  filter(year != 2016)

hiv.data <- hiv.data %>%
  filter(year != 2015)

hiv.data <- hiv.data %>%
  filter(year != 2014)

hiv.data <- hiv.data %>%
  filter(year != 2013)

# The HIV database doesn't have 2006 or 2007. I'm going to remove those from the ARCOS database.

arcos_county_pills_per_year <- arcos_county_pills_per_year %>%
  filter(year !=2006) 
  
  
arcos_county_pills_per_year <- arcos_county_pills_per_year %>% 
  filter(year !=2007)

```

```{r}

# Changing names in ARCOS dataframe to match HIV dataframe

arcos_county_pills_per_year <- arcos_county_pills_per_year %>% 
  #setnames(old=c("buyer_state"), new=c("state"))
  setnames(old=c("buyer_county"), new=c("county"))


# Removing FIPS from ARCOS dataframe

  arcos_county_pills_per_year <- arcos_county_pills_per_year %>%
  subset(select = -c(countyfips))


```

```{r}

# Joining HIV data with ARCOS data

hiv_and_pills <- merge(hiv.data, arcos_county_pills_per_year, by=c("year","county", "state")) 

```


```{r}

# Q5: How many counties do we have data for once we do the join? 
 
# A: 11,344. That's less than half of what we started with. Seems problematic. Maybe I will have to     focus on one state? Or a handful of states?

# Now I want to figure out how to get rid of the unnecessary columns. 

hiv_and_pills <- hiv_and_pills %>%
  subset(select = -c(year.x,buyer_state))

```

```{r}

hiv_and_pills <- hiv_and_pills %>%
  subset(select = -c(buyer_county))

```

```{r}
#
#Now I want to clean up the column names and rearrange their order. 

hiv_and_pills %>%
  #setnames(old=c("rate_per_100000"), new=c("hiv_rate")) 
  #setnames(old=c("year.y"), new=c("year")) 
  #setnames(old=c("count"), new=c("shipments")) 
  #setnames(old=c("cases"), new=c("hiv_cases")) 

```

```{r}

hiv_and_pills <- hiv_and_pills[c("fips", "county", "state", "year", "shipments", "dosage_unit", "hiv_cases", "hiv_rate", "population")]

```

```{r}

# Make a column for pills per person.


#hiv_and_pills <- hiv_and_pills %>% 
   #mutate(population = as.(population))

#glimpse(hiv_and_pills)


#hiv_and_pills <- hiv_and_pills %>%
 #mutate(pills_per_person=dosage_unit/population)



```

```{r}

#Q6: Which county had the most pills per person during this time?

hiv_and_pills %>%
  arrange(desc(pills_per_person))

# A: According to that code, it was Oakland County, MI. However, I do not trust this, because its population is listed as 4. How could a county with 4 people have 1,398 cases of HIV in 2012? There is clearly a problem here. I do not know what it is.


```

```{r}

#Q7: What the hell is wrong with the population column? In the original HIV dataset, Oakland County had a population of more than 1,000,000. Now, it says it has a population of 4. Something clearly went wrong with the join. 

hiv.data %>%
  arrange(desc(population))

# OKAY so it might be because the population was listed as a "factor" column in the OG dataset. Let me go back and fix that and try everything again. 

# UPDATE: This mutation of the population and dosage_units column is clearly breaking everything. It has something to do with the way the population column is formatted. I've been on stackoverflow and other sites for close to an hour, and can't figure out why it's messing everything up. That will have to wait until later. (I went back and commented that last chunk out.)

# What I did figure out, though, is that the join is messed up because the CSV axed off any "0"s that led off a FIPS code. I'm going to try and fix that.

# UPDATE (about an hour after the last update): After an absolutely hellish process, I have come to the conclusion that I will need Sean's help to figure out this issue with the FIPS code. For now, I'll analyze all the results I am able to get with the join.

```

```{r}

# Q8: Which county had the highest rate of HIV diagnoses in 2012?

hiv_and_pills %>%
  filter(year=="2012") %>%
  arrange(desc(hiv_rate))

# A: Calhoun County, GA.

```

```{r}

#Q9: Is there any HIV rate pattern when this data is grouped by state in the year 2012?

hiv_and_pills %>%
  filter(year=="2012") %>%
  group_by(state) 

# A: It's hard to tell, and this clearly isn't perfect code for the job. I'm going to try a different approach.

```

```{r}

# Q10: I'm going to zero in on some specific states. What was up with Florida in 2012?

hiv_and_pills %>%
  filter(year=="2012", state=="FL") %>%
  arrange(desc(hiv_rate))


# A: Something is wrong with these columns, yet again. Looks like they are factors, which means they can't be properly sorted in a numeric way. But every time I try to fix that, the numbers get clearly skewed.

```


